### ISSUE TITLE
Chance of adding VS2013 project files?

### ISSUE THREAD

**Issue by ghost** [EmperorArthur/VBA-M#15]
http://sourceforge.net/p/vbam/code/1247/ added VS2013 project/solution files. Adding these to your project may make building on Windows easier (VS2013 is now free for open source projects)

**Comment by DoctorWho11** [comment]
That would build the mfc interface. Not the wxwidgets interface. To be honest cmake is rather the easiest to work with. Can generate makefiles, or project files.

**Comment by voltagex** [comment]
Are there any instructions for building with Windows? I can't get cmake to
find zlib - on Linux I'd just install a -dev package but there's no
equivalent on Windows. I have built the zlib lib file with VS2013, though.

**Comment by DoctorWho11** [comment]
Right now compiling is a bit borked on windows. I've been slowly importing his changes into the official vba-m svn repository. To build I suggest getting msys2 which contains pacman package manager from linux and install the packages that way msys2.github.io is the address

**Comment by EmperorArthur** [comment]
The latest svn is on svn-master.
I'm currently working on merging it and master together.

There are a decent bit of merge conflicts, mostly due to spacing issues, so it might take me a little while.

**Comment by DoctorWho11** [comment]
The spacing issues was making code a little more readable
it really doesn't look good with stuff having like 

void something;
{
blah
b;ah
}

so I'm working to make it more like
void something;
{
      blah
      blah
}

**Comment by EmperorArthur** [comment]
DoctorWho11:
That's not really the problem.
The issue is my editor puts 4 spaces instead of tabs, but it looks like yours uses actual tabs.
Basically, almost every line of the patch file I sent you turned into a merge conflict.

All:
Please take a look at the svn-merge branch to see how well this first try at merging went.
I'm probably going to redo it, using git cherry-pick, but this is a start.

**Comment by ghost** [comment]
Did anyone end up taking a second look?

**Comment by ZachBacon** [comment]
@voltagex not really. At the moment though, myself and a few others are looking to include some of the changes into our git master at https://github.com/visualboyadvance-m/visualboyadvance-m there we also have made some other improvements like sdl2 integration etc

**Comment by ghost** [comment]
Cool, will close this in favour of that work.
