### ISSUE TITLE
Title of project is misleading

### ISSUE THREAD

**Issue by DoctorWho11** [EmperorArthur/VBA-M#9]
Just to let you know vba-m.com is not unmaintained. I'm one of the devs of vba-m and we haven't abandoned the project, just we do a lot of things and we also have lives that take a lot of our time. I do thank you though for showing concern with the project though. I'll look through the changes you made and see about streaming them up in the svn repo. I also noticed the patches in the tracker there too that I assume are from you too. EDIT: Ok not title but project description I meant

**Comment by EmperorArthur** [comment]
Thank you for your feedback, and for helping to make VBA-M what it is today.

When I started this fork, the svn had not been updated in several months, and I saw all those patches just sitting in the bug tracker.  Seeing official development pick up would be a joy.

My changes can be broken down into a few major areas.
1.  Getting VBA-M working with modern libraries.
2.  Modularizing the different guis.  This mostly involved splitting the cmake files, but did involve changing the artwork directory.
3.  Unifying the filter framework.

Progress:
1. VBA-M now compiles on modern Linux distributions, but the link functionality doesn't work correctly.
2. Pretty much done
3. I've moved all the filters into one directory, and the WX gui now selects among them based on the filter's name.  I will next look at the SDL and GTK guis.

I have not touched the windows gui as I do not currently have a Windows Dev machine.

**Comment by DoctorWho11** [comment]
Well my excuse for not developing in a while was due to personal issues (some of which is yet to be resolved but it's getting to the point where I'm deving again) As for the sfml2 the reason that patch was overlooked was that it has some current issues with linking, Now Squall didn't exactly go into detail (He rarely does and imho he's a bit of a pain to actually talk to) So for now I'll keep that one seperate, probably as a seperate branch for now, but the SDL2 and other front end improvements look good. One goal I have in mind for the gtk interface if you are still interested in lending a hand, is to migrate the current gtk core code to gtk 3. specifically when gtk 3.16 comes out there is an opengl widget that could be used that would help gtk side widdle down on a dependency of gtkglextmm, though personally I think after the migration of the wxwidgets code to wxwidgets 3.x, could kill off the gtk and even the mfc interface.

**Comment by EmperorArthur** [comment]
I'm trying to think of a better description for the project page.  Any input you have would be greatly appreciated.

The SFML2 stuff isn't ready yet.  The showstiopper for WX was fixed in e1730ad611d974dc761de70ecdf0354b5b40b9c8

Another showstopper was Cmake actually compiling with wxwidgets 3, instead of throwing an error.  The program would compile, but not run properly.  It was fixed in a series of patches ending with this one 291e08b6043296692dbdedbd0e2411bd322666f8

When I actually have time, I'll try to turn my changes into usable patches for you to apply.

**Comment by DoctorWho11** [comment]
I say let's keep your repo going, use it as a test bed for absolute new changes to sfml2 etc and then when it's right merge it into svn

**Comment by EmperorArthur** [comment]
I've gone ahead and compiled a diff for the Cmake build system on Linux machines.  Including changing the art asset location.  I'll post the link as soon as I can find a place to host it.

This will at least solve the issue of CMake trying to compile with WX 3 even if 2.8 is installed.

**Comment by DoctorWho11** [comment]
Go to http://vba-m.com send it as a private message to TheCanadianBacon for now.

**Comment by EmperorArthur** [comment]
The website wasn't working with attachments, so I've just E-Mailed the patches to the address you use on your git commits.
